all:
	gcc -Wall -o lexer lexer.c
	
run:
	./lexer -i Arithmetic.p
	./lexer -i Assign.p
	./lexer -i Comment.p
	./lexer -i Sort.p
	./lexer -i SquareRoot.p
	./lexer -i TokenList.p
	./lexer -i CommentError.p
	./lexer -i Error.p